services:

  ping:
    build:
      context: frontend
      args:
        - NEXT_PUBLIC_REDIRECT_URI=${REDIRECT_URI}
        - NEXT_PUBLIC_CLIENT_ID=${CLIENT_ID}
        - CLIENT_SECRET=${CLIENT_SECRET}
    ports:
      - 3000:3000
    depends_on:
      - pong
    restart: always

  pong:
    build: backend
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./backend/media:/media
      - ./backend/static:/static
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    image: postgres
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis
    restart: always

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: always

  nginx:
    image: nginx
    ports:
      - 8000:8000
    volumes:
      - ./backend/static:/static:ro
      - ./backend/media:/media:ro
      - ./nginx/ft_transcendence.conf:/etc/nginx/conf.d/ft_transcendence.conf
    depends_on:
      - pong
    restart: always
