name: ft_transcendence-actions

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the project
    - run: yes | sh generate-env.sh
    - run: docker compose up --build --detach
