name: Docker Image CI

on:
  push:
    branches: [ "main", "frontend" ]
  pull_request:
    branches: [ "main", "frontend" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the project
      run: docker compose up --build --detach
